apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: itzchaktunik-dev
spec:
  type: NodePort  # Change to LoadBalancer if using cloud provider
  ports:
    - protocol: TCP
      port: 3307
      targetPort: 3307
      nodePort: 30007 # Optional, for NodePort type
  selector:
    app: mysql